### PR TITLE
Feat: Added Forgot password component

### PR DESCRIPTION
**Pull request by ShekharDhangar**
Added forgot password component
image

### CODE REVIEW

**Review by vrx29 — COMMENTED** [review]
Try to remove extra divs and try it with appropriate semantic tags.

**Comment by ShekharDhangar** [comment]
> Try to remove extra divs and try it with appropriate semantic tags.

Removed in latest commit

**Review by vrx29 — APPROVED** [review]
Looks good now

**Review by VLeads — APPROVED** [review]
Code looks good !

**Pull request merged**
