### PR TITLE
feat: Wishlist-page

### PR DESCRIPTION
**Pull request by ShekharDhangar**
Added Wishlist-page. Click on heart-icon for directing to Wishlist page. Please give your reviews

### CODE REVIEW

**Review by partha8 — COMMENTED** [review]
a suggestion, add justify-content: center and align-items: center to product-container because the cards are not aligned properly in full screen.

Screenshot (33)

**Review by partha8 — APPROVED** [review]
Overall good work!

**Comment by ShekharDhangar** [comment]
> a suggestion, add justify-content: center and align-items: center to product-container because the cards are not aligned properly in full screen.
> 
> Screenshot (33)

Made the changes

**Review by nayyyhaa — APPROVED** [review]
Nice & clean UI. One suggestion in product-listing page, while hovering over the cards you could add some transition for ease, rest good work. 💯

**Pull request merged**
